### ISSUE TITLE
amq tests are failing

### ISSUE THREAD

**Issue by jwendell** [jboss-openshift/ce-testsuite#112]
@rimolive @alesj do you guys have some wip branch that we can use as a starting point in order to fix amq tests?

**Comment by alesj** [comment]
@jwendell not really ...

You need to wait for my jboss-dockerfile changes to be merged in,
and new images created off those scripts.

Plus, we'll need to go off my temp "repl" application template in most of the tests.

So, you either live with this current failures, or you disable / ignore those tests.

**Comment by rimolive** [comment]
Fixed in Pull Requests #120, #125, #129, #132 and #133.
