### ISSUE TITLE
webserver tests are failing

### ISSUE THREAD

**Issue by jwendell** [jboss-openshift/ce-testsuite#152]
one of the reasons is that multiple template are being used in class hierarchy (for example in the classes WebServerTomcat7BasicSecureTest and its parent WebServerTomcat7BasicTest). In this case they should be refactored to let onle one class instantiate the template.

see https://github.com/jboss-openshift/ce-arq/issues/55 for the rationale.

**Comment by rcernich** [comment]
If this is going to force us to refactor all the existing tests, then I vote we modify the new multi template logic to only pick the first @Template(s) annotation it finds in the class hierarchy.

**Comment by jwendell** [comment]
I think only kieserver and webserver were affected. The first one is already fixed by @errantepiphany (looking forward for your pr, David :))

**Comment by jwendell** [comment]
@rimolive or @spolti can some of you guys take care of this?

**Comment by errantepiphany** [comment]
https://issues.jboss.org/browse/CLOUD-1256
https://github.com/jboss-openshift/ce-testsuite/pull/154

--
David Ward
Senior Software Engineer, Cloud Enablement
Red Hat, Inc.

**Comment by jwendell** [comment]
Fixed by 8e65ce2b33f263ff1d476f59ac6b932bf3690e01
