### ISSUE TITLE
Kieserver doesn't compile

### ISSUE THREAD

**Issue by jwendell** [jboss-openshift/ce-testsuite#171]
It incorrectly points to a snapshot version of ce-arq, introduced by b0c06f509156e37bce851e1e5e30f9bdf7c0e720.

We should not rely on snapshots, instead, as of today, we rely on ce-arq 1.0.1.Final.
Moreover, we shouldn't tag the version in children modules, we should rely on parent pom defining the version we must use, just like other modules.

**Comment by errantepiphany** [comment]
Here is a PR that should fix this:
https://github.com/jboss-openshift/ce-testsuite/pull/172
