### ISSUE TITLE
SSO tests failing

### ISSUE THREAD

**Issue by jwendell** [jboss-openshift/ce-testsuite#176]
Sso70Eap64AllInOneTest is failing due to wrong credentials.
I believe the fix for this is:
1. Add SSO_ADMIN_USERNAME and SSO_ADMIN_PASSWORD to templates in openshift-examples repo
2. Add those parameters to ce-tests like done in 3fe842ddd932baa92fdab60066595179fc723ae1

@wdecoste Any opinion on this?

**Comment by bdecoste** [comment]
Shouldn't be that. I tested all of these tests last week and they were passing. The all-in-one tests set the admin user/password with the import config file. I'll check this Wed when I am back. Thanks for the heads up

**Comment by jwendell** [comment]
This is fixed for a long time...
