### ISSUE TITLE
Tests are running with mode="class". Should be running as mode="suite"

### ISSUE THREAD

**Issue by rimolive** [jboss-openshift/ce-testsuite#95]
Having a single namespace to all test classes would speed up the tests. Let's consider use mode="suite" for our project.

**Comment by rcernich** [comment]
The issue with suite is that the test pod gets created once, at the beginning of all tests, which means it will be missing the service related environment variables.  This is why they are using class, so the environment injected into to the pod contains the service related entries for the system under test.

If we go this route, we'll need to find a different means of resolving the services (e.g. dns, hard coded ports, etc.).
